### ISSUE TITLE
链接整理

### ISSUE THREAD

**Issue by JiYouMCC** [JiYouMCC/zamsub#119]
是想整理所有的链接按钮：

1. 更新日志https://github.com/JiYouMCC/zamsub/issues?q=is%3Aissue+label%3Aupdate
2. 纠错https://github.com/JiYouMCC/zamsub/issues/new?labels=bug&template=----.md&title=纠错%3A+XX站数据错了%2F其他错误描述
3. 提交更新https://github.com/JiYouMCC/zamsub/issues/new?labels=update&template=-------.md&title=yyyymmdd地铁更新%3A+XX线添加XX站%26XX线移动XX站
4. 仓库主页https://github.com/JiYouMCC/zamsub
--------
5. 关于本站（？）增加一个页面介绍这是啥，写上贡献者名字

**Comment by JiYouMCC** [comment]
@magicbottle 现在右上角的2个按钮能满足你的需求吗

**Comment by magicbottle** [comment]
@JiYouMCC 你應該@紙鹿，我沒需求
