### ISSUE TITLE
20190909-1003及震後更新：K3線 方舟線 雪國線 K14線 北境線 K17線 K11線 K12線 K13線

### ISSUE THREAD

**Issue by magicbottle** [JiYouMCC/zamsub#129]
**K3線**
- 添加 羊莊站 (1079, 40, 999)
- 添加 奇蹟之洞站 (988, 40, 1181)

**方舟線**
- 添加 方舟線 #006600
- 添加 綠寶石站 (2282, 40, 1349)

**雪國線**
- 添加 北境平原站 (-4600, 40, -6901) **注意與北境線同名站位置不同！**

**K14線**
- 添加 稻香村站 (-2524, 40, -1)
- 添加 聖梟堡站 (-2810, 40, -1)
- 添加 游泳圈的家站 (-3260, 40, -1)

**北境線**
- 添加 北境線 #0000FF
- 添加 北境平原站 (-4528, 71, -6896) **注意與雪國線同名站位置不同！**
- 添加 霧之湖中心地標點站 (-4073, 74, -6896)

**K17線**
- 添加 聖梟堡站 (-2810, 40, -1)
- 添加 兔島站 (-2809, 20, -650)

**K11線**
- 併入 K17線

**K12線**
- 添加 中世紀現代小鎮站 (-2001, 40, -1986)

**K13線**
- 添加 綠寶石站 (2245, 40, 1347) **此站震後位置改變**

@JiYouMCC @Tinigam

**Comment by JiYouMCC** [comment]
北境平原我要实地考察一下
那个瞎眼线怎么办

**Comment by magicbottle** [comment]
瞎眼線手動例外一下顯示黑字？我看其實蘋果地圖好像就是這麼幹的

**Comment by JiYouMCC** [comment]
晕 怎么积累了那么多

**Comment by JiYouMCC** [comment]
雪国线那个同名站 技术上不支持，就和当年的地下城站一个情况。
想办法同名吧

**Comment by magicbottle** [comment]
那就加括號咯

**Comment by magicbottle** [comment]
大媽正好咕了一個月

**Comment by JiYouMCC** [comment]
@magicbottle 稻之港在K14上有站点吗
