### ISSUE TITLE
20191010地铁更新: 北境平原站和北境平原（北境线）站合并

### ISSUE THREAD

**Issue by JiYouMCC** [JiYouMCC/zamsub#132]
**北境线 雪国线**
- 经过实地考察，两个北境平原站可以合并为一个双站台车站，由换乘通道和标示牌子连接。
- 魔瓶也许需要更改一下牌子，比如“要乘坐北境线，请上楼到XXXX”之类的

@JiYouMCC @magicbottle

**Comment by magicbottle** [comment]
好
