### ISSUE TITLE
地狱冰道更新调研

### ISSUE THREAD

**Issue by JiYouMCC** [JiYouMCC/zamsub#185]
- 研究一下怎么把冰道加上来
- 冰道现在和地铁站并不一定一一对应是吧
- 让用户选打钩打叉是否坐冰道
- 冰道现在速度如何

**Comment by magicbottle** [comment]
對應名稱的冰道出口和地鐵站也可能要走一段距離才能換乘。

**Comment by JiYouMCC** [comment]
干脆叫 XXX地狱门算了，坐标写成地狱门的坐标
回头我到处晃一圈看看怎么弄

**Comment by magicbottle** [comment]
冰道出口和地獄地獄門都是直連的，但地鐵站和主世界地獄門不一定。

**Comment by JiYouMCC** [comment]
正好被更新了 等魔瓶造完了继续调研

**Comment by magicbottle** [comment]
經典拖著拖著活ㄦ沒了。

**Comment by JiYouMCC** [comment]
哈哈哈~~~其实我挺怀念从彩虹半岛冰岛去花花坡村的，那么近
