### ISSUE TITLE
路径显示带线路颜色

### ISSUE THREAD

**Issue by JiYouMCC** [JiYouMCC/zamsub#2]

**Comment by Tinigam** [comment]
線路	顏色
K1線	#3399CC
愛國線	#66CCCC
少女前線	#FFCCFF
K2線	#999999
K3線	#996600
東方線	#CC00FF
二狗線	#9999CC
K4線北段	#CC6699
K4線南段	#CC6699
K5線	#99CCFF
髮如雪線	#99FF33
參宿線	#0099CC
K6線	#FF9999
雪國線	#CCCCCC
德意志線	#FF9900
奧茲線	#FFCC00
K7線	#FF6633
K8線	#99CCCC
M1線	#3399FF
K9線	#CC9999
K10線	#33CC66
K11線	#CC6600
K12線	#FF3399
K13線	#339999
K14線	#990000
K15線	#003366
贊①線	#FF0000
贊②線	#000066
X專線	#336699
比利線	#003399
魚塔線	#FF00FF
新風線	#FF0099
伊蘇線	#0066CC

**Comment by JiYouMCC** [comment]
接着就是推这个issue了 :imp:

**Comment by JiYouMCC** [comment]
考虑了一下，还是用svg做 :grinning:

**Comment by JiYouMCC** [comment]
![3ef4dcfc90503f2d](https://user-images.githubusercontent.com/7357434/53218490-46f60280-3697-11e9-9c37-5717703d284b.jpg)

**Comment by JiYouMCC** [comment]
線路	顏色
贊①線	#FF0000
贊②線	#000066
X專線	#336699
比利線	#003399
魚塔線	#FF00FF
新風線	#FF0099
伊蘇線	#0066CC
波止線	#66CCFF
風光線	#339900
血汗線	#CCFFFF
呂梨線	#996699

**Comment by JiYouMCC** [comment]
線路	顏色
K1線	#3399CC
愛國線	#66CCCC
少女前線	#FFCCFF
K2線	#999999
K3線	#996600
東方線	#CC00FF
二狗線	#9999CC
K4線北段	#CC6699
K4線南段	#CC6699
K5線	#99CCFF
髮如雪線	#99FF33
參宿線	#0099CC
K6線	#FF9999
雪國線	#CCCCCC
德意志線	#FF9900
奧茲線	#FFCC00
K7線	#FF6633
K8線	#99CCCC
M1線	#3399FF
K9線	#CC9999
K10線	#33CC66
K11線	#CC6600
K12線	#FF3399
K13線	#339999
K14線	#990000
K15線	#003366
