### ISSUE TITLE
核实酸柠檬的家站坐标

### ISSUE THREAD

**Issue by JiYouMCC** [JiYouMCC/zamsub#221]
![image](https://user-images.githubusercontent.com/7357434/90216639-ad458680-de31-11ea-8aee-b1a11a36ef7a.png)
 酸柠檬的坐标是不是错了

_Originally posted by @JiYouMCC in https://github.com/JiYouMCC/zamsub/issues/195#issuecomment-673891385_

**Comment by JiYouMCC** [comment]
@magicbottle

**Comment by magicbottle** [comment]
z=-2270
