### ISSUE TITLE
增加清空，起点终点交换按钮和找到茬了链接

### ISSUE THREAD

**Issue by JiYouMCC** [JiYouMCC/zamsub#23]

**Comment by Tinigam** [comment]
找到茬了是啥

**Comment by magicbottle** [comment]
（還有計算最近地鐵站什麼的（手動滑稽

**Comment by JiYouMCC** [comment]
@Tinigam “找到茬了”就是提供一个连接到这里，如果有问题让他们直接提issue(手动360°兔子转脑袋)

**Comment by JiYouMCC** [comment]
图标库选择
https://octicons.github.com/

**Comment by JiYouMCC** [comment]
图标选择2：https://fontawesome.com/start

https://fontawesome.com/icons/eraser?style=solid 清空（橡皮擦）
https://fontawesome.com/icons/exchange-alt?style=solid 交换（左右交换）
https://fontawesome.com/icons/comment-alt?style=solid 评论
https://fontawesome.com/icons/code?style=solid 代码图标
