### ISSUE TITLE
地铁站信息标签页

### ISSUE THREAD

**Issue by JiYouMCC** [JiYouMCC/zamsub#27]
（還有計算最近地鐵站什麼的（手動滑稽

_Originally posted by @magicbottle in https://github.com/JiYouMCC/zamsub/issues/23#issuecomment-450783853_

信息

1. 站点名称
2. 照片（300*300, gif 尽量空间小）原版材质，没有光影，车站外景或者车站外面和车站名相关的地标建筑（某某的家，一条上海老江，盘丝洞的刷怪笼，之类的），尽量白天，不要飞行模式，史蒂夫视野 /img/station_caihongbandao.gif
3. 一句话简介， 目测15个字以下包括标点
4. 站台坐标（程序计算）
5. 站台类型（这有用吗）
6. 出口 （需要实地考察，我在考虑要不要加上这个）
7. 临近站点 （程序计算）
8. 连接线路 （程序计算）

连接线路和临近站点上可以加上超链接，以后可以加上线路的标签信息页面

![untitled_page](https://user-images.githubusercontent.com/7357434/54796659-0be1f180-4c8c-11e9-8659-d06051ed86c9.png)

**Comment by magicbottle** [comment]
座標制之後這個可以不咕咕了（

**Comment by JiYouMCC** [comment]
这个我在想是不是在站点上加个预览页面什么的 这个可以好好设计一下呢

# 彩虹半岛
[此处有图片一张]
## 坐标
XX,XX,XX
## 简介
巴拉巴拉巴拉巴拉
## 最近的5个站点
- 彩虹镇洲际酒店 XX米
- XXXXX XX米
- XXXXX XX米
- XXXXX XX米
- XXXXX XX米
## 住户
- 大妈
- 谁谁
- 谁谁

类似于这样的

**Comment by JiYouMCC** [comment]
:pencil2: 感兴趣的人可以用手绘一下界面，给点灵感什么的

**Comment by magicbottle** [comment]
https://zamcraft-railway.fandom.com/zh/wiki/魔瓶的家?variant=zh-hant

這個我之前有計畫做個wiki來著。。。不過要走的路還很長。。。

**Comment by JiYouMCC** [comment]
@magicbottle 好棒好棒

# 车站名称
【此处有图片一张】
这里是简介巴拉巴拉巴拉
## 车站坐标
- 第一个坐标
- 第二个坐标
## 站台类型
XXXXX
## 车站出口
- 出口1： 通往XX
- 出口2： 通往XX
## 周围建筑
- 谁谁的家
- 某某房子
## 最近的5个站点
- XXXXX XX米
- XXXXX XX米
- XXXXX XX米
- XXXXX XX米
- XXXXX XX米
## 线路信息
- XX线
- XX线
## 车站管理
赞铁一局

**Comment by JiYouMCC** [comment]
推荐一个玩具给大家玩 http://pencil.evolus.vn/

Ji You <notifications@github.com> 于2019年3月21日周四 上午10:44写道：

**Comment by JiYouMCC** [comment]
![_C__Users_yecx_Documents_GitHub_zamsub_station html(iPhone X) (1)](https://user-images.githubusercontent.com/7357434/54805643-8887c680-4cb2-11e9-8f1d-c4d875128e97.png)
初稿
