### ISSUE TITLE
车站坐标录入

### ISSUE THREAD

**Issue by JiYouMCC** [JiYouMCC/zamsub#3]

**Comment by Tinigam** [comment]
录入已完成

**Comment by magicbottle** [comment]
另外可以考慮一下輸入起點/終點座標給出最近車站？

**Comment by JiYouMCC** [comment]
我上次不是给了一个例子，距离彩虹半岛5分钟内的所有站点嘛。。。各种脑洞

**Comment by Tinigam** [comment]
魔瓶的意思應該是說輸入當前玩家的坐標然後查找離玩家最近的地鐵站怎麼走？ 就和地圖軟件的查找地鐵站功能一樣

**Comment by Tinigam** [comment]
其實真的可以做成地圖！類似於A點向東南方向行走xxx米抵達a站，坐地鐵到b站，再從x號出站口出去向西北方向行走yyy米抵達B點

**Comment by magicbottle** [comment]
差不多是這個意思
