### ISSUE TITLE
ico 征集

### ISSUE THREAD

**Issue by JiYouMCC** [JiYouMCC/zamsub#30]
在没有人抗议之前，我就用“魔瓶秒啊”作为图标，就这么愉快地决定了

**Comment by JiYouMCC** [comment]
![miaoa](https://user-images.githubusercontent.com/7357434/51008036-f57d3280-1584-11e9-9494-9a1d9f5d3a97.jpg)
![miaoa](https://user-images.githubusercontent.com/7357434/51008039-f746f600-1584-11e9-8f0e-a160440d18e1.png)
![tuzi](https://user-images.githubusercontent.com/7357434/51008043-f910b980-1584-11e9-845d-89ee7461d6c8.png)
几个版本的图片备份

**Comment by magicbottle** [comment]
那我抗議🌚
