### ISSUE TITLE
K5线南端延申至沙漠枢纽（风之镇-风之镇西-沙漠枢纽）

### ISSUE THREAD

**Issue by Tinigam** [JiYouMCC/zamsub#31]
风之镇[-788, 40, 1737]
风之镇西[-1256, 56, 1863]
沙漠枢纽为K5线北段/新风线原有的站
顺带一提K5线南段北段就从这里连上了

**Comment by magicbottle** [comment]
更正：提尼尬母熬夜熬傻了，只是K5線風之鎮與沙漠樞紐之間增加風之鎮西站而已。

**Comment by Tinigam** [comment]
更新完毕
