### ISSUE TITLE
楚格峰和新手村的坐标一样

### ISSUE THREAD

**Issue by JiYouMCC** [JiYouMCC/zamsub#56]
'楚格峰': {
        	'location': [-1839, 40, -4501]
        },
        '新手村': {
        	'location': [-1839, 40, -4501]
        },

**Comment by JiYouMCC** [comment]
:angry: 我去 谁干的

**Comment by Tinigam** [comment]
血汗线：#CCFFFF
楚格峰: (-1839, 40, -4501)
距离2115
新手村: (-3954, 40, -4501)
正在改....
