### ISSUE TITLE
把狼窝加进起点呗

### ISSUE THREAD

**Issue by AoneWildernessWolf** [JiYouMCC/zamsub#6]
就是中央枢纽到目的地的距离加上狼窝到中央枢纽距离。据地铁信息提供的坐标算，距离大概是749

**Comment by Tinigam** [comment]
已加入， 等待上传

**Comment by JiYouMCC** [comment]
合并到Tinigam的Branch里面了，我想可能会再拉个branch单独merge，不然可能会咕咕咕。。
