### ISSUE TITLE
20190221地铁更新: K1线延长至妹控镇南&K6线增加支线妹控客栈

### ISSUE THREAD

**Issue by JiYouMCC** [JiYouMCC/zamsub#66]
**地铁K1线**
- 北线延长到妹控镇南

**地铁K6线**
- 支线添加妹控客栈(-405,39,-2064)

**特殊要求**
妹控客栈仅与妹控镇南双向互通

@JiYouMCC @Tinigam

@magicbottle 就这么填

**Comment by magicbottle** [comment]
哦。
